### ISSUE TITLE
OGN wiki: example is importing parse_ogn_beacon, but it is not defined

### ISSUE THREAD

**Issue by Krelyshy** [Meisterschueler/ogn-python#141]
Hello,
on [http://wiki.glidernet.org/dev-python](OGN wiki) there is an example showing how to "connect to OGN and display all incoming beacons". That example is trying to import function parse_ogn_beacon, which I can not find anywhere... maybe I am just blind, but can I ask where is this function located?

from ogn.client import AprsClient
from ogn.parser import parse_aprs, parse_ogn_beacon, ParseError
 
def process_beacon(raw_message):
    if raw_message[0] == '#':
        print('Server Status: {}'.format(raw_message))
        return
 
    try:
        beacon = parse_aprs(raw_message)
        beacon.update(parse_ogn_beacon(beacon['comment']))
 
        print('Received {beacon_type} from {name}'.format(**beacon))
    except ParseError as e:
        print('Error, {}'.format(e.message))
 
client = AprsClient(aprs_user='N0CALL')
client.connect()
 
try:
    client.run(callback=process_beacon, autoreconnect=True)
except KeyboardInterrupt:
    print('\nStop ogn gateway')
    client.disconnect()

Thank you in advance :-)

**Comment by Krelyshy** [comment]
I do not know why github highlights the non problematic section... that highlightning is irrelevant to the problem.

**Comment by acasadoalonso** [comment]
Just type

from ogn.parser import parse

And use the parse function to parse the APRS messages ... all kind of APRS messages

AC/.

**Comment by Meisterschueler** [comment]
Hello @Krelyshy, the ogn wiki is a little bit outdated, but currently I cannot login and modify it. In the meantime please look here for the ogn parser:
[https://github.com/glidernet/python-ogn-client](python-ogn-client)

**Comment by Krelyshy** [comment]
Ok, thank you.
