### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by kerel-fs** [Meisterschueler/ogn-python#5]
Nice python module, collecting common tasks for ogn
(ognutils.py and some regexps were a déjà-vu :smile: ).

To enable others to contribute, please add a license (eg. GPLv3).
<http://choosealicense.com/>

It would be nice if it evolves to a proper python-standard-module for ogn.
(currently there are implementations using the c-extension libfap,
the python-module aprslib and raw sockets)

Btw: I would recommend to rename the repo `ogn-python` like the ogn-fork did.

**Comment by Meisterschueler** [comment]
Thank you, I add a license and renamed the project
