### ISSUE TITLE
Request for help

### ISSUE THREAD

**Issue by nferruzzi** [Meisterschueler/ogn-python#59]
Hello,
I've been able to deploy and run the whole thing using docker and docker-compose for the dependencies, as soon I'm sure is working fine Ill commit them somewhere.
Yet, I'm not so sure everything is running ok, I can see the list of devices and receivers being populated, but the only data they have are address, name and altitude. 
Also in the gateway run log all I got are
"ERROR in bulkimport: Ignore beacon_type: flymaster" and from the code it look it doesn't recognize the data.

Could you please drive me around this?
thanks in advance

**Comment by Meisterschueler** [comment]
Hi, just added "flymaster" as valid beacon, so the error message should disappear.

**Comment by Meisterschueler** [comment]
Device should not be empty. You should see something like this:

![Bildschirmfoto 2019-09-11 um 08 55 20](https://user-images.githubusercontent.com/4268343/64674828-fa76e680-d471-11e9-97b6-8e0ae3eab370.png)

Are your celery jobs running?

**Comment by nferruzzi** [comment]
Thank you, at the end celery wasn't running. I still have a lot of missing details; but finally I completed porting the deploy to docker and now I will leave it running for 1 day waiting for it to populate properly. I have borders, world altitute and few cups. Hopefully this will be enough to see more data. I open you a PR for docker, in case you may be intereted
